docs: example requires `example` feature to run (#2451)
## Description

You will get this error without passing `--features=examples`.

```bash
🐡 ❯ cargo run --example client
error: target `client` in package `iroh` requires the features: `examples`
Consider enabling them by passing, e.g., `--features="examples"
```

## Breaking Changes

No.

## Notes & open questions

<!-- Any notes, remarks or open questions you have to make about the PR.
-->

## Change checklist

- [ ] Self-review.
- [ ] Documentation updates if relevant.
- [ ] Tests if relevant.
- [ ] All breaking changes documented.


Closes #2431