Bump bytes minimum version to 1.4 (#903)
Adding iroh to a project that already depended on bytes 1.1 fails to compile with:

```
error[E0599]: no function or associated item named `zeroed` found for struct `BytesMut` in the current scope
   --> /home/fabrice/dev/capyloon/api-daemon/third-party/iroh/src/get.rs:273:36
    |
273 |     let mut out_buffer = BytesMut::zeroed(std::cmp::max(
    |                                    ^^^^^^ function or associated item not found in `BytesMut`
```

Because `BytesMut::zeroed()` was introduced in 1.2 . This PR sets the version to 1.4 which is the current stable version for the `bytes` crate.