feat(iroh-cli): improve ergonomics of `iroh gossip subscribe` CLI cmd (#2751)
## Description

<!-- A summary of what this pull request achieves and a rough list of
changes. -->

Previously the gossip command could be confusing:
```sh
$ iroh gossip subscribe test --start
error: invalid value 'test' for '[BOOTSTRAP]...': decoding: base32: non-zero trailing bits at 3
```

Now, the output is more helpful:
```sh
$ iroh gossip subscribe test --start
error: the following required arguments were not provided:
  <--topic <TOPIC>|--raw-topic <RAW_TOPIC>>

Usage: iroh gossip subscribe --start <--topic <TOPIC>|--raw-topic <RAW_TOPIC>> <BOOTSTRAP>...

For more information, try '--help'.
```

And the help text also contains examples & explanation on how the
command works.

## Breaking Changes

<!-- Optional, if there are any breaking changes document them,
including how to migrate older code. -->
None. The command still works the same way.

## Notes & open questions

Closes #2698

Should we rename the command? When I read `gossip subscribe` initially,
I thought a `gossip publish` command may be missing. But actually
`gossip subscribe` does both.
Perhaps `gossip join` may be better?
But also: We want to keep the CLI names in sync with the names in the
code API. Perhaps we should rename the API call to be `join` instead of
`subscribe`? Or perhaps something like `open_topic`?
Anyhow - perhaps that's food for thought & another PR.


## Change checklist

- [x] Self-review.
- [x] Documentation updates following the [style
guide](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text),
if relevant.
- ~~[ ] Tests if relevant.~~
- [x] All breaking changes documented.

Co-authored-by: Friedel Ziegelmayer <me@dignifiedquire.com>