chore: Remove `cc` version requirement & update lockfile to cc v1.2.1 (#2969)
## Description

<!-- A summary of what this pull request achieves and a rough list of
changes. -->

This was getting in my way when I was trying to install both iroh &
iroh-blobs from their main branches in a project.

<details>
<summary>cargo check output</summary>

```sh
$ cargo check
    Updating git repository `https://github.com/n0-computer/iroh`
    Updating git repository `https://github.com/n0-computer/iroh-blobs`
    Updating crates.io index
error: failed to select a version for `cc`.
    ... required by package `ring v0.17.8`
    ... which satisfies dependency `ring = "^0.17"` (locked to 0.17.8) of package `iroh-net v0.28.1`
    ... which satisfies dependency `iroh-net = "^0.28.1"` (locked to 0.28.1) of package `iroh v0.28.1 (https://github.com/n0-computer/iroh?branch=main#e675bbaf)`
    ... which satisfies dependency `iroh = "^0.28.1"` (locked to 0.28.1) of package `quickstart-iroh v0.1.0 (/home/philipp/program/work/quickstart-iroh)`
versions that meet the requirements `^1.0.83` (locked to 1.2.1) are: 1.2.1

all possible versions conflict with previously selected packages.

  previously selected package `cc v1.1.31`
    ... which satisfies dependency `cc = "=1.1.31"` of package `iroh v0.28.1 (https://github.com/n0-computer/iroh?branch=main#e675bbaf)`
    ... which satisfies dependency `iroh = "^0.28.1"` (locked to 0.28.1) of package `quickstart-iroh v0.1.0 (/home/philipp/program/work/quickstart-iroh)`

failed to select a version for `cc` which could resolve this conflict
```

</details>

Version 1.2 should now fix all the issues we had with it.
@dignifiedquire can you check again that this doesn't break your build
pretty please (I remember you [having issues
before](https://discord.com/channels/949724860232392765/950683937661935667/1304050364076527646)).

## Change checklist

- [x] Self-review.
- ~~[ ] Documentation updates following the [style
guide](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text),
if relevant.~~
- ~~[ ] Tests if relevant.~~
- ~~[ ] All breaking changes documented.~~